# config.toml
# https://github.com/CrimsonRay/slender

baseurl = "//yknx4.github.io/blog"
# baseurl = ""
title = "[ Y k N x ]"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"
canonifyurls = true

[Taxonomies]
	tag = "tags"
	category = "categories"

[author]
    name = "Jorge Alejandro Figueroa Pérez"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]


    subtitle = "4"
    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "<bold>Life</bold><small>Thoughts, </small><bold>Social</bold><small>Criticism</small><small>, and some </small><bold>Software</bold><small>Development</small>"

    # Footer; Markdown accepted here.
    footer = "Copyright 2015 &copy; J Alejandro Figueroa"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Yknx - Jorge Figueroa. Personal blog about Tech, Software and Life"
    keywords = "yknx,yknx4,jorge figueroa, jorge alejandro figueroa perez, software, development, life, technology"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:yknx.4.b+contact@gmail.com"
    github = "//www.github.com/yknx4"
    # bitbucket = "url-to-your-bitbucket"
    twitter = "//twitter.com/yknx4"
    # stackoverflow = "url-to-your-stackoverflow"
    linkedin = "//mx.linkedin.com/in/yknx4"
    facebook = "//www.facebook.com/yknx4"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "UA-74724455-1"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/blog"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"
    weight     = 4

		[[menu.main]]
		identifier = "categories"
		name = "categories"
		url = "categories/"
		weight = 2

		[[menu.main]]
		identifier = "tags"
		name = "tags"
		url = "tags/"
		weight = 3

		[[menu.main]]
		identifier = "pro"
		name = "pro"
		url = "https://yknx4.github.io"
		weight = 5
